server:
  port: ${PORT:8080}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.security.autoconfigure.ReactiveUserDetailsServiceAutoConfiguration

  application:
    name: rest_api

  profiles:
    active:
      - ${ACTIVE_PROFILE:local}
    group:
      test:
        - test
      local:
        - local
      dev:
        - dev
      prod:
        - prod

  output:
    ansi:
      enabled: always
